#Copyright Contributors to the Open Cluster Management project.

apiVersion: apps/v1
kind: Deployment
metadata:  
  name: {{ .Values.ClusterCuratorController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.ClusterCuratorController.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: {{ .Values.ClusterCuratorController.name }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.ClusterCuratorController.name }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.hubconfig.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.ClusterCuratorController.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.ClusterCuratorController.name }}
        ocm-antiaffinity-selector: "cluster-curator-controller"
    spec:
      {{- if .Values.global.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.global.imagePullSecret }}
      {{- end }}
      {{- with .Values.clusterCuratorAffinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      tolerations:
      - key: dedicated
        operator: Exists
        effect: NoSchedule
      - effect: NoSchedule 
        key: node-role.kubernetes.io/infra 
        operator: Exists

      serviceAccountName: {{ .Values.ClusterCuratorController.shortName }}
      hostNetwork: false
      hostPID: false
      hostIPC: false
      securityContext:
        runAsNonRoot: true
      containers:
      - command: ["/bin/sh","-c"]
        args: ["./cluster-curator-controller || ./manager -enable-leader-election"]
        image: "{{ .Values.global.imageOverrides.cluster_curator_controller }}"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_URI
          value: "{{ .Values.global.imageOverrides.cluster_curator_controller }}"
        imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
        name: {{ .Values.ClusterCuratorController.name }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
        resources:
{{ toYaml .Values.ClusterCuratorController.resources | indent 10 }}
      {{- with .Values.hubconfig.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 8 }}
      {{- end }}
